### PR TITLE
add 'block' property value highlighting

### PR DESCRIPTION
**Pull request by faergeek**
It's strange, but `block` isn't highlighted.

``` css
.whatever {
  display: block;
}
```

### CODE REVIEW

**Comment by i-akhmadullin** [comment]
Oops, seems like i forgot to push fixed version, 'block' highlight should be fixed after package update or sublime restart.
Thank you for taking your time to fix this anyway.

**Comment by faergeek** [comment]
Seems like you forgot to merge. Or I don't understand something?

**Comment by i-akhmadullin** [comment]
I have fixed this bug in 534cd1b0666e7c712f80388ea078c405a46df8f6 but forgot to upload changes in github repo.

**Comment by faergeek** [comment]
Great! Thanks.

**Pull request closed without merging**
